-- Tworzenie tabeli 'roles'
CREATE TABLE public.roles (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  level INT UNIQUE NOT NULL
);

-- Wstawianie domyślnych ról
INSERT INTO public.roles (name, level) VALUES
('Officer', 1),
('Sergeant', 2),
('Lieutenant', 3),
('Captain', 4),
('High Command', 5)
ON CONFLICT (name) DO NOTHING;

-- Tworzenie tabeli 'divisions'
CREATE TABLE public.divisions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT
);

-- Wstawianie domyślnych dywizji
INSERT INTO public.divisions (name, description) VALUES
('Patrol Division', 'Odpowiedzialna za patrole i reagowanie na zgłoszenia.'),
('Detective Bureau', 'Prowadzi dochodzenia w sprawach kryminalnych.'),
('Traffic Division', 'Zajmuje się egzekwowaniem przepisów ruchu drogowego.'),
('SWAT Team', 'Jednostka specjalna do zadań wysokiego ryzyka.')
ON CONFLICT (name) DO NOTHING;

-- Tworzenie tabeli 'profiles'
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  badge_number TEXT UNIQUE NOT NULL,
  first_name TEXT,
  last_name TEXT,
  role_id INT REFERENCES public.roles(id) DEFAULT 1 NOT NULL, -- Domyślnie 'Officer'
  division_id INT REFERENCES public.divisions(id),
  status TEXT DEFAULT 'pending' NOT NULL, -- 'pending', 'approved', 'rejected'
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Włączanie Row Level Security (RLS) dla tabeli 'profiles'
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Polityka RLS: Użytkownicy mogą czytać swoje własne profile
CREATE POLICY "Users can view their own profile." ON public.profiles
  FOR SELECT USING (auth.uid() = id);

-- Polityka RLS: Użytkownicy mogą aktualizować swoje własne profile
CREATE POLICY "Users can update their own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Polityka RLS: Użytkownicy mogą tworzyć profile (po rejestracji)
CREATE POLICY "Users can create profiles." ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

-- Polityka RLS: Administratorzy (High Command) mogą czytać wszystkie profile
CREATE POLICY "High Command can view all profiles." ON public.profiles
  FOR SELECT TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles AS p_admin
      JOIN public.roles AS r_admin ON p_admin.role_id = r_admin.id
      WHERE p_admin.id = auth.uid() AND r_admin.name = 'High Command'
    )
  );

-- Polityka RLS: Administratorzy (Lieutenant, Captain, High Command) mogą aktualizować status, role i dywizje
CREATE POLICY "Admins can manage user accounts." ON public.profiles
  FOR UPDATE TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles AS p_admin
      JOIN public.roles AS r_admin ON p_admin.role_id = r_admin.id
      WHERE p_admin.id = auth.uid() AND r_admin.level >= (SELECT level FROM public.roles WHERE name = 'Lieutenant')
    )
  ) WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles AS p_admin
      JOIN public.roles AS r_admin ON p_admin.role_id = r_admin.id
      WHERE p_admin.id = auth.uid() AND r_admin.level >= (SELECT level FROM public.roles WHERE name = 'Lieutenant')
    )
  );

-- Tworzenie bucketu 'avatars' w Supabase Storage
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Polityka RLS dla bucketu 'avatars': Każdy może przesyłać i pobierać awatary
CREATE POLICY "Avatar images are publicly readable." ON storage.objects
  FOR SELECT USING (bucket_id = 'avatars');

CREATE POLICY "Anyone can upload an avatar." ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'avatars');

CREATE POLICY "Anyone can update their own avatar." ON storage.objects
  FOR UPDATE USING (auth.uid() = owner) WITH CHECK (bucket_id = 'avatars');