-- Tabela Ról
CREATE TABLE IF NOT EXISTS public.roles (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL UNIQUE,
    level integer NOT NULL
);

-- Tabela Dywizji
CREATE TABLE IF NOT EXISTS public.divisions (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL UNIQUE,
    description text
);

-- Tabela Profili
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email text UNIQUE NOT NULL,
    badge_number text UNIQUE NOTING NULL,
    first_name text,
    last_name text,
    role_id integer REFERENCES public.roles(id),
    status text DEFAULT 'pending' NOT NULL, -- 'pending', 'approved', 'rejected'
    avatar_url text
);

-- Tabela relacji Profile-Division (wiele do wielu)
CREATE TABLE IF NOT EXISTS public.profile_divisions (
    profile_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    division_id integer REFERENCES public.divisions(id) ON DELETE CASCADE,
    PRIMARY KEY (profile_id, division_id)
);

-- Tabela Ogłoszeń
CREATE TABLE IF NOT EXISTS public.announcements (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    title text NOT NULL,
    content text NOT NULL
);

-- Tabela Raportów
CREATE TABLE IF NOT EXISTS public.reports (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    recipient_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    title text NOT NULL,
    location text,
    date date,
    time text,
    description text NOT NULL,
    priority text DEFAULT 'medium' NOT NULL,
    status text DEFAULT 'Oczekujący' NOT NULL -- 'Oczekujący', 'W toku', 'Zakończony', 'Odrzucony'
);

-- Tabela Notatek Operacyjnych
CREATE TABLE IF NOT EXISTS public.notes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    author_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    title text NOT NULL,
    content text NOT NULL
);

-- Tabela Udostępniania Notatek
CREATE TABLE IF NOT EXISTS public.note_shares (
    note_id uuid REFERENCES public.notes(id) ON DELETE CASCADE,
    profile_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    PRIMARY KEY (note_id, profile_id)
);

-- Tabela Pinów w Dossier
CREATE TABLE IF NOT EXISTS public.officer_pins (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    target_profile_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    
    note_id uuid REFERENCES public.notes(id) ON DELETE CASCADE,
    report_id uuid REFERENCES public.reports(id) ON DELETE CASCADE,
    
    CONSTRAINT check_one_document CHECK (
        (note_id IS NOT NULL AND report_id IS NULL) OR 
        (note_id IS NULL AND report_id IS NOT NULL)
    )
);

-- Tabela Udostępniania Pinów
CREATE TABLE IF NOT EXISTS public.officer_pin_shares (
    pin_id uuid REFERENCES public.officer_pins(id) ON DELETE CASCADE,
    profile_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    PRIMARY KEY (pin_id, profile_id)
);

-- Wstawianie domyślnych ról
INSERT INTO public.roles (name, level)
VALUES 
    ('Officer', 1),
    ('Sergeant', 2),
    ('Lieutenant', 3),
    ('Captain', 4),
    ('High Command', 5)
ON CONFLICT (name) DO NOTHING;